export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES:SUCCESS';
export const GET_IMAGES_FAILED = 'GET_IMAGES:FAILED';
export const LOAD_IMAGES = 'LOAD_IMAGES';
export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES:SUCCESS';
export const LOAD_IMAGES_FAILED = 'LOAD_IMAGES:FAILED';
export const SET_IMAGE = 'SET_IMAGE';